### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by momotsow** [osamaashraf6/Space-X-React-Group#25]
For this project, we are working as a team of two namely: Khomotso Mkansi and Osama Ashraf

[Link for the project](https://github.com/osamaashraf6/Space-X-React-Group
)
[Link for the Kanban project](https://github.com/users/osamaashraf6/projects/3/views/1)

**Comment by emmiiorji** [comment]
Hi @momotsow, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Invalid](https://user-images.githubusercontent.com/20554583/208471563-6e107df6-d81c-4e39-b90a-9659d619116f.gif)

You have submitted an project with a [broken link](https://github.com/users/osamaashraf6/projects/3/views/1) for the Kanban board. Kindly confirm that the link is correct. If you're yet to create the kanban board, kindly follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by momotsow** [comment]
Hi @emmiiorji Our project was just private we have now made it public

**Comment by osamaashraf6** [comment]
- Thanks @emmiiorji 🙏 for reviewing our issue I appreciate your review  we solved the problem💯 
### Thanks again for reviewing our Issue and have a good day😊

**Comment by jerryowusu** [comment]
Hello Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![clapping-leonardo-dicaprio](https://user-images.githubusercontent.com/65233860/208480410-6237fcfe-6539-4dc0-908f-f7af47716e69.gif)


## Highlights
Nice set up for Kanban board :heavy_check_mark: 
Project tasks evenly distributed :+1: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
